### ISSUE TITLE
codegen: org.freedesktop.timesync1 interface is missing

### ISSUE THREAD

**Issue by mguentner** [lucab/zbus_systemd#39]
Thanks for this useful crate.

It would be nice if the above mentioned interface can be provided as well. I'd like to manage ntp servers with zbus / rust but currently need to resort to generating the trait myself:

`zbus-xmlgen --system org.freedesktop.timesync1 /org/freedesktop/timesync1`

**Comment by lucab** [comment]
Thanks for the report, I didn't realize so far that the crate is missing the `timesync1` interface.

The codebase here is generated from the static XML description in the upstream `systemd` repo, and unfortunately it looks like the `org.freedesktop.timesync1` entry is directly missing there.

I've opened https://github.com/systemd/systemd/issues/34352 to track the missing XML description in `systemd` source.
Once the XML file is added to the upstream repo and lands in a `systemd` release, we can pick it up here and generate the corresponding module.

**Comment by mguentner** [comment]
Thanks!
