### ISSUE TITLE
codegen: org.freedesktop.sysupdate1 interface is missing

### ISSUE THREAD

**Issue by lucab** [lucab/zbus_systemd#40]
A new `org.freedesktop.sysupdate1` interface has been added to the `systemd` suite in https://github.com/systemd/systemd/pull/32363.
It will be first released in next major upstream version (`257`).

This is a reminder to add the relevant codegen config and generate the new `sysupdate1` module, once the new upstream release is out.

**Comment by lucab** [comment]
@AdrianVovk thanks for the heads-up! I think that's ok, `zbus_systemd` is version-locked with `systemd`.
That is, the current `v0.25600.0` matches systemd `v256`, and that way we can deal with interfaces changes across 257/258/etc.

**Comment by AdrianVovk** [comment]
Interesting. Unless otherwise stated (like sysupdated), systemd's dbus APIs are stable and backwards compatible. So in theory you don't need to version-lock like this
