### ISSUE TITLE
connect_system_dbus is unneeded and confusing.

### ISSUE THREAD

**Issue by blueForestIcarus** [lucab/zbus_systemd#5]
It seems that the connect_system_dbus function is the same as zbus::Connection::system(), and is not systemd specific in any way.

I think providing it is just confusing, why not have users use the zbus function?

**Comment by lucab** [comment]
Thanks for the report. 
I do not disagree with your statement :smile:, feel free to send a PR to drop it and port the examples to plain `zbus`.

At the same time, this crate is very much far from being mature. I would expect several helper functions to grow over time, but they can be always added later.
For reference, the Go native library has several connection helpers that grew up over the years: https://pkg.go.dev/github.com/coreos/go-systemd/v22@v22.4.0/dbus
